provider:
  name: ubicloud
data_sources:
  firewall:
    read:
      path: /project/{project_id}/location/{location}/firewall/{firewall_reference}
      method: GET
    schema:
      attributes:
        aliases:
          firewall_reference: name
      ignores:
        - private_subnets
        - firewall_rules.protocol
        - firewall_rules.description
  firewall_rule:
    read:
      path: /project/{project_id}/location/{location}/firewall/{firewall_reference}/firewall-rule/{firewall_rule_id}
      method: GET
    schema:
      attributes:
        aliases:
          firewall_rule_id: id
  private_subnet:
    read:
      path: /project/{project_id}/location/{location}/private-subnet/{private_subnet_reference}
      method: GET
    schema:
      attributes:
        aliases:
          private_subnet_reference: name
  project:
    read:
      path: /project/{project_id}
      method: GET
    schema:
      attributes:
        aliases:
          project_id: id
  vm:
    read:
      path: /project/{project_id}/location/{location}/vm/{vm_reference}
      method: GET
    schema:
      attributes:
        aliases:
          vm_reference: name
      ignores:
        - boot_image
        - ip4_enabled
        - gpu
        - firewalls.firewall_rules.protocol
        - firewalls.firewall_rules.description
  postgres:
    read:
      path: /project/{project_id}/location/{location}/postgres/{postgres_database_reference}
      method: GET
    schema:
      attributes:
        aliases:
          postgres_database_reference: name
      ignores:
        - flavor
        - target_server_count
        - target_storage_size_gib
        - target_version
        - target_vm_size
        - ca_certificates
        - maintenance_window_start_at
        - read_replica
        - parent
        - fallback_active
        - tags
        - created_at
        - username
        - password
        - hostname
        - firewall_rules.description
        - firewall_rules.port
resources:
  firewall:
    create:
      path: /project/{project_id}/location/{location}/firewall/{firewall_reference}
      method: POST
    read:
      path: /project/{project_id}/location/{location}/firewall/{firewall_reference}
      method: GET
    schema:
      attributes:
        aliases:
          firewall_reference: name
      ignores:
        - private_subnets
  firewall_rule:
    create:
      path: /project/{project_id}/location/{location}/firewall/{firewall_reference}/firewall-rule
      method: POST
    read:
      path: /project/{project_id}/location/{location}/firewall/{firewall_reference}/firewall-rule/{firewall_rule_id}
      method: GET
    schema:
      attributes:
        aliases:
          firewall_rule_id: id
  vm:
    create:
      path: /project/{project_id}/location/{location}/vm/{vm_reference}
      method: POST
    read:
      path: /project/{project_id}/location/{location}/vm/{vm_reference}
      method: GET
    schema:
      attributes:
        aliases:
          vm_reference: name
      ignores:
        - ip4
        - ip6
        - state
        - storage_size_gb
        - firewalls
        - id
        - ip4_enabled
        - private_ipv4
        - private_ipv6
        - storage_size_gib
        - subnet
  postgres:
    create:
      path: /project/{project_id}/location/{location}/postgres/{postgres_database_reference}
      method: POST
    read:
      path: /project/{project_id}/location/{location}/postgres/{postgres_database_reference}
      method: GET
    schema:
      attributes:
        aliases:
          postgres_database_reference: name
          vm_size: size
      ignores:
        - connection_string
        - earliest_restore_time
        - latest_restore_time
        - state
        - ca_certificates
        - created_at
        - fallback_active
        - firewall_rules
        - hostname
        - id
        - maintenance_window_start_at
        - parent
        - password
        - primary
        - read_replica
        - storage_size_gib
        - target_server_count
        - target_storage_size_gib
        - target_version
        - target_vm_size
        - username
        - vm_size
  private_subnet:
    create:
      path: /project/{project_id}/location/{location}/private-subnet/{private_subnet_reference}
      method: POST
    read:
      path: /project/{project_id}/location/{location}/private-subnet/{private_subnet_reference}
      method: GET
    schema:
      attributes:
        aliases:
          private_subnet_reference: name
  project:
    create:
      path: /project
      method: POST
    read:
      path: /project/{project_id}
      method: GET
    schema:
      attributes:
        aliases:
          project_id: id
