name: Acceptance Tests

on:
  workflow_dispatch:

jobs:
  acceptance:
    runs-on: ubicloud

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: make install
        run: make install

      - name: make testacc
        run: make testacc
        env:
          UBICLOUD_ACC_TEST_PROJECT: ${{ vars.UBICLOUD_ACC_TEST_PROJECT }}
          UBICLOUD_ACC_TEST_LOCATION: ${{ vars.UBICLOUD_ACC_TEST_LOCATION }}
          UBICLOUD_ACC_TEST_FIREWALL: ${{ vars.UBICLOUD_ACC_TEST_FIREWALL }}
          UBICLOUD_ACC_TEST_PRIVATE_SUBNET: ${{ vars.UBICLOUD_ACC_TEST_PRIVATE_SUBNET }}
          UBICLOUD_API_TOKEN: ${{ secrets.UBICLOUD_API_TOKEN }}
          TF_LOG: DEBUG
